ARG BASE_IMAGE=ghcr.io/infinity-swap/ic-dev-base:latest
ARG IC_BIN_IMAGE=ghcr.io/infinity-swap/ic-bin:latest

FROM $IC_BIN_IMAGE as ic_bin

FROM $BASE_IMAGE
ARG WORK_DIR=$WORK_DIR
ENV DFX_WASMS_DIR=${WORK_DIR}/wasm

WORKDIR $WORK_DIR


COPY --from=ic_bin --chown=root:root /ic/wasm $WORK_DIR/wasm
COPY --from=ic_bin --chown=root:root /ic/ic-nns-init /usr/local/bin/

RUN (cd $DFX_WASMS_DIR && curl -SsO https://storage.googleapis.com/dfx-server_ic/testnet/wasm/is20_token.wasm)

RUN chmod -R 0777 wasm
RUN chmod -R 0755 /usr/local/bin

RUN echo "Packed binaries" && ls -la /usr/local/bin

RUN echo "Packed canisters" && ls -la $DFX_WASMS_DIR


COPY dfx.json nns/setup.sh nns/initial-neurons.csv ${WORK_DIR}/
RUN chmod -R 0777 setup.sh

EXPOSE 8000

USER root

RUN ls

ARG IC_URI="http://localhost:8000"

RUN /bin/bash -c "export IC_URI=$IC_URI DFX_WASMS_DIR=wasm SCRIPT_DIR=.\
 && dfx start --clean --background" && ./setup.sh

RUN mkdir ${WORK_DIR}/candid

#CMD dfx start --host 0.0.0.0:8000 --background 

